apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: techchallenge
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "techchallange-customer"

  CORS_ALLOWED_ORIGINS: "https://tech-challenge-front.vercel.app,http://localhost:5173"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "3600"