apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-customer-service
  namespace: techchallenge
  labels:
    app: tech-challenge-customer-service
spec:
  selector:
    app: tech-challenge-customer-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP